{% set version = "2.0" %}
{% set sha256 = "21483f4f07db1ba3f127b67e2b7c5b19bea1d2a4d6069006f124a3a3086a9697" %}

package:
  name: scripttest
  version: "{{ version }}"

source:
  fn: scripttest-{{ version }}.tar.gz
  url: https://github.com/pypa/scripttest/archive/{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - scripttest

about:
  home: https://github.com/pypa/scripttest
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: 'Helper to test command-line scripts.'
  dev_url: https://github.com/pypa/scripttest
  doc_url: https://scripttest.readthedocs.io

extra:
  recipe-maintainers:
    - dmaticzka
