travis:
  secure:
    BINSTAR_TOKEN: FQsTv3+rXv+4G/T/C9e61cUfpFz18I5vSkWiH6rUCck4XqyXQd4HilbqbKti1ofbyUl4K+ozH4MKgduTbXSog/IHqfwlYXPXulWACPIB7gcNJP95HOEvwXg1OTU9+qlh0gBFPwhCldQqVks0VjKcdAbG7iGk3RkgJ2YbZ9Sd1camw5MCn2jgJsry+sSkjrbXAhRzKzq//nMItJ7EFrYQeLg+cO6G+Kq963WfSSV0+XMPN86zv5Rgv5HmTyWkcB9QOSAylkPOOLcWR5I79BWQugF6tyOgu8xlarhrKqmxlxbMUIWYfUvTqTFXhBVqsM454A2jL7JJWPza/5WdvWcsJsKQEitylsy8ABSgR7FrASbDlooWIj+LDt9f5Az4ZC1gZzaqvtKpipy8unLg0ocAvRfuQV1n0KC/OqBz+/ses6lRn44BDDWqGv+vfa4nXmGEtXOz+e4++gSdFoLRNOERYH2lcMdarx4HQjeC8/+XGvVkeomms7dkM/R7lK9pjbIv//fe0F5ZESBXUq2BDA8T0kOSCmZy7Xb82ZtIOdQ48ZGh3ZG5VNtDLPAOyY4LqwCtcdY/DXwi8QbQXfvndmANiY77G3POx4y6BkDEUeJbsfafG4cGx+cqiMcEq2eFettlOf9M1nr6U5i5/JX5W5tkNaWJloB5bOfMp/0hyv9w6kI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
